### ISSUE TITLE
Remote server and client not working(advanced tutorial with mnist)

### ISSUE THREAD

**Issue by klize** [OpenMined/PySyft#2946]
**Describe the bug**

Currently i am trying to play federated learning with syft on one machine, and planning to extends to multiple ones.

os : ubuntu 18.04
python : 3.6
virtualenv

1. i create two venvs for server and client respectively with python3.6
2. pip install syft[udacity]
3. pip install syft-proto (This is also an issue that only with the step 2, syft-proto is not installed. Moreover, I must modify the line `from pysyft-proto import proto_info` into `from syft-proto import proto_info` in syft/serde/proto.py)
4. write server script and run it
5. write client script and run it

First I summarize my issues and questions:
In summary:
1. `pip install syft[udacity]` does not include `syft-proto`
2. `syft/serde/proto.py` must be modified:.
    * `from pysyft-proto ...` -> `from syft-proto ...`
3. Server yields `RuntimeWarning: coroutine 'WebsocketServerWorker._consumer_handler' was never awaited` after client connection.
4. client is quited immediately after `clinet.connect()` excuted
5. Why do i have to declare lines about server class in `examples/tutorials/websocket/WebsocketClientWorker.ipynb` ?

**To reproduce**
Details:

I installed syft[udacity] by `pip install syft[udacity]` on two virtualenvs of server and client.
I just copied `run_websocket_server.py` into my server script and turned it on.
```python
from multiprocessing import Process
import torch
import os
import logging
import argparse

import syft as sy
from syft.workers.websocket_server import WebsocketServerWorker

hook = sy.TorchHook(torch)

def start_proc(participant, kwargs):  # pragma: no cover
    """ helper function for spinning up a websocket participant """

    def target():
        server = participant(**kwargs)
        server.start()

    p = Process(target=target)
    p.start()
    return p

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Run websocket server worker.")
    parser.add_argument(
        "--port", "-p", type=int, help="port number of the websocket server worker, e.g. --port 8777"
    )
    parser.add_argument("--host", type=str, default="localhost", help="host for the connection")
    parser.add_argument(
        "--id", type=str, help="name (id) of the websocket server worker, e.g. --id alice"
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="if set, websocket server worker will be started in verbose mode",
    )

    args = parser.parse_args()

    kwargs = {
        "id": args.id,
        "host": args.host,
        "port": args.port,
        "hook": hook,
        "verbose": args.verbose,
    }
    server = start_proc(WebsocketServerWorker, kwargs)
```
```bash
python server.py --port 8282 --host localhost --id server -v
```

And for my client script, I **removed** some lines in examples/tutorials/websocket/WebsocketClientWorker.ipynb as I want to play this on seperate machines later
```python
hook = syft.TorchHook(torch)

local_worker = WebsocketServerWorker(
                            host='localhost',
                            hook=hook,
                            id=0,
                            port=8182,
                            log_msgs=True,
                            verbose=True)

hook = syft.TorchHook(torch, local_worker=local_worker)
```
I think the above was written under the consideration of the same machine.

So finally I run below as a client just for a test connection:
```python
import torch

import os
import sys

import syft as sy
from syft.workers.websocket_client import WebsocketClientWorker

hook = sy.TorchHook(torch)

client = WebsocketClientWorker(host='localhost',hook=hook, id=0, port=8282, log_msgs=True, verbose=True, is_client_worker=True)

client.connect()
```
```bash
python client.py
```
Here is my logs diplayed on the terminals:
Server:
```
Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '.../venv/lib/python3.6/site-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.15.0.so'
WARNING:tensorflow:From .../venv/lib/python3.6/site-packages/tf_encrypted/session.py:24: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Serving. Press CTRL-C to stop.
# This lines pop right after the client.connect() is excuted.
...server/venv/lib/python3.6/site-packages/syft/workers/websocket_server.py:93: RuntimeWarning: coroutine 'WebsocketServerWorker._consumer_handler' was never awaited
  self._consumer_handler(websocket)

```

Client
```
Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was .../venv/lib/python3.6/site-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.15.0.so'
WARNING:tensorflow:From ...client/venv/lib/python3.6/site-packages/tf_encrypted/session.py:24: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

```
The client script is exited immetiately.

Am I using in a wrong way ? or websocket is not fully supported yet?

**Comment by klize** [comment]
removing `client.connect()` yields the same error

**Comment by karlhigley** [comment]
> syft/serde/proto.py must be modified:. from pysyft-proto ... -> from syft-proto ...

This part has been addressed in v0.2.2 of PySyft, which was just recently released.

**Comment by karlhigley** [comment]
> pip install syft[udacity] does not include syft-proto

@klize Could you submit a PR to fix this? Would be much appreciated!

**Comment by klize** [comment]
I am sorry to be late due to a long break.
I've just installed again `pip install syft[udacity]` and checked the requirements on `syft-proto` has been already merged in some PR. 

But the websocket connection is not resolved in v0.2.2a1, I got still same errors with my packages

Package              Version      
-------------------- -------------
absl-py              0.9.0        
astor                0.8.1        
certifi              2019.11.28   
chardet              3.0.4        
Click                7.0          
Flask                1.1.1        
Flask-SocketIO       4.2.1        
gast                 0.2.2        
google-pasta         0.1.8        
grpcio               1.26.0       
h5py                 2.10.0       
idna                 2.8          
itsdangerous         1.1.0        
Jinja2               2.11.0       
Keras-Applications   1.0.8        
Keras-Preprocessing  1.1.0        
lz4                  3.0.2        
Markdown             3.1.1        
MarkupSafe           1.1.1        
msgpack              0.6.2        
numpy                1.18.1       
opt-einsum           3.1.0        
phe                  1.4.0        
Pillow               6.2.2        
pip                  20.0.2       
pkg-resources        0.0.0        
protobuf             3.11.2       
python-engineio      3.11.2       
python-socketio      4.4.0        
PyYAML               5.3          
requests             2.22.0       
scipy                1.4.1        
setuptools           45.1.0       
six                  1.14.0       
syft                 0.2.2a1      
syft-proto           0.1.1a1.post2
tblib                1.6.0        
tensorboard          1.15.0       
tensorflow           1.15.2       
tensorflow-estimator 1.15.1       
termcolor            1.1.0        
tf-encrypted         0.5.9        
torch                1.3.0        
torchvision          0.4.1        
urllib3              1.25.8       
websocket-client     0.57.0       
websockets           8.1          
Werkzeug             0.16.1       
wheel                0.34.1       
wrapt                1.11.2       
zstd                 1.4.4.0      

I got these ones with `pip install syft[udacity]` and `pip install requests`.

**Comment by jimmoffet** [comment]
I'm having a similar problem using the containerized workers (built from the unmodified pysyft-worker docker image) and the toy example from /examples/deploy_workers:

```
import torch
import syft
from syft import WebsocketClientWorker

hook = syft.TorchHook(torch)

alice = WebsocketClientWorker(hook=hook, id="alice", host='127.0.0.1', port=8777)

t = torch.tensor([73, 74, 75])
ta = t.send(alice)

print(ta.get())
```

It fails on t.send, here's what the worker reports:

> alice_1  | Task exception was never retrieved
> alice_1  | future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /usr/local/lib/python3.6/site-packages/syft/workers/websocket_server.py:95> exception=IndexError('tuple index out of range',)>
> alice_1  | Traceback (most recent call last):
> alice_1  |   File "/usr/local/lib/python3.6/site-packages/syft/workers/websocket_server.py", line 113, in _producer_handler
> alice_1  |     response = self._recv_msg(message)
> alice_1  |   File "/usr/local/lib/python3.6/site-packages/syft/workers/websocket_server.py", line 124, in _recv_msg
> alice_1  |     return self.recv_msg(message)
> alice_1  |   File "/usr/local/lib/python3.6/site-packages/syft/workers/base.py", line 285, in recv_msg
> alice_1  |     msg = sy.serde.deserialize(bin_message, worker=self)
> alice_1  |   File "/usr/local/lib/python3.6/site-packages/syft/serde/serde.py", line 351, in deserialize
> alice_1  |     return _detail(worker, simple_objects)
> alice_1  |   File "/usr/local/lib/python3.6/site-packages/syft/serde/serde.py", line 543, in _detail
> alice_1  |     return detailers[obj[0]](worker, obj[1])
> alice_1  |   File "/usr/local/lib/python3.6/site-packages/syft/messaging/message.py", line 207, in detail
> alice_1  |     return ObjectMessage(sy.serde._detail(worker, msg_tuple[1]))
> alice_1  | IndexError: tuple index out of range

For good measure, here's what the main process reports:

> WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tf_encrypted/session.py:24: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
> 
> Websocket connection closed (worker: alice)
> Created new websocket connection
> Traceback (most recent call last):
>   File "master.py", line 12, in <module>
>     ta = t.send(alice)
>   File "/usr/local/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 419, in send
>     garbage_collect_data=garbage_collect_data,
>   File "/usr/local/lib/python3.6/site-packages/syft/workers/base.py", line 395, in send
>     self.send_obj(obj, worker)
>   File "/usr/local/lib/python3.6/site-packages/syft/workers/base.py", line 607, in send_obj
>     return self.send_msg(ObjectMessage(obj), location)
>   File "/usr/local/lib/python3.6/site-packages/syft/workers/base.py", line 277, in send_msg
>     bin_response = self._send_msg(bin_message, location)
>   File "/usr/local/lib/python3.6/site-packages/syft/workers/virtual.py", line 7, in _send_msg
>     return location._recv_msg(message)
>   File "/usr/local/lib/python3.6/site-packages/syft/workers/websocket_client.py", line 104, in _recv_msg
>     "Websocket connection closed and creation of new connection failed."
> RuntimeError: Websocket connection closed and creation of new connection failed.
> Exception ignored in: <bound method ObjectPointer.__del__ of [PointerTensor | me:32028884160 -> alice:11842207604]>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/syft/generic/pointers/object_pointer.py", line 344, in __del__
>     self.owner.send_msg(ForceObjectDeleteMessage(self.id_at_location), self.location)
>   File "/usr/local/lib/python3.6/site-packages/syft/workers/base.py", line 277, in send_msg
>     bin_response = self._send_msg(bin_message, location)
>   File "/usr/local/lib/python3.6/site-packages/syft/workers/virtual.py", line 7, in _send_msg
>     return location._recv_msg(message)
>   File "/usr/local/lib/python3.6/site-packages/syft/workers/websocket_client.py", line 92, in _recv_msg
>     response = self._forward_to_websocket_server_worker(message)
>   File "/usr/local/lib/python3.6/site-packages/syft/workers/websocket_client.py", line 87, in _forward_to_websocket_server_worker
>     response = binascii.unhexlify(self.ws.recv()[2:-1])
>   File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 314, in recv
>     opcode, data = self.recv_data()
>   File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 331, in recv_data
>     opcode, frame = self.recv_data_frame(control_frame)
>   File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 344, in recv_data_frame
>     frame = self.recv_frame()
>   File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 378, in recv_frame
>     return self.frame_buffer.recv_frame()
>   File "/usr/local/lib/python3.6/site-packages/websocket/_abnf.py", line 361, in recv_frame
>     self.recv_header()
>   File "/usr/local/lib/python3.6/site-packages/websocket/_abnf.py", line 309, in recv_header
>     header = self.recv_strict(2)
>   File "/usr/local/lib/python3.6/site-packages/websocket/_abnf.py", line 396, in recv_strict
>     bytes_ = self.recv(min(16384, shortage))
>   File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 453, in _recv
>     return recv(self.sock, bufsize)
>   File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 115, in recv
>     "Connection is already closed.")
> websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
